### ISSUE TITLE
What type of image (in terms of size) is being pulled with this?

### ISSUE THREAD

**Issue by philkeys** [scottdixon/react-native-upload-from-camera-roll#3]
Just wondering if this is grabbing the original size that was taken from the camera or if only grabbing a thumbnail or smaller file. I believe it to be grabbing the thumbnail since the base64 output is only a few kb's, and if so is there a setting I can adjust to have it grab another size. 

Thanks

**Comment by scottdixon** [comment]
Try modifying this line:
https://github.com/scottdixon/react-native-upload-from-camera-roll/blob/master/RCTCustom.m#L26

Instead of `thumbnail`, you're after `defaultRepresentation`.

https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAsset_Class/#//apple_ref/occ/instm/ALAsset/defaultRepresentation

**Comment by alubling** [comment]
@scottdixon - hey Scott, it looks like `defaultRepresentation` was deprecated in ios 9.0? Any idea what this should change to now?

**Comment by scottdixon** [comment]
@alubling - looks like the `Photos framework` replaced it: https://developer.apple.com/library/ios/documentation/Photos/Reference/Photos_Framework/index.html#//apple_ref/doc/uid/TP40014408

The existing code will need some massaging to replace it.

**Comment by alubling** [comment]
@scottdixon - yeah looks like it. Thanks Scott.

For now we just modified to this, instead of the thumbnail:

`ALAssetRepresentation *representation = [asset defaultRepresentation];
 CGImageRef imageRef = [representation fullResolutionImage];`

`// this is for resizing the image
   UIImage *actualImage = [UIImage imageWithCGImage:imageRef];
   UIGraphicsBeginImageContext(CGSizeMake(800, 800));
   [actualImage drawInRect:CGRectMake(0,0,800, 800)];
   UIImage* newImage = UIGraphicsGetImageFromCurrentImageContext();
   UIGraphicsEndImageContext();
   NSData *imageData = UIImageJPEGRepresentation(newImage, 0.1);`
